# SPDX-FileCopyrightText: 2025 TNG Technology Consulting GmbH <info@tngtech.com>
#
# SPDX-License-Identifier: GPL-2.0-only

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.1.1
    hooks:
      - id: reuse
