# SPDX-FileCopyrightText: 2025 TNG Technology Consulting GmbH <info@tngtech.com>
#
# SPDX-License-Identifier: GPL-2.0-only

services:
  sbom:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace/LinuxKernelSbomGenerator
    working_dir: /workspace/LinuxKernelSbomGenerator
    command: >
      python3 sbom.py
        --src-tree ../linux
        --output-tree ../linux/kernel-build
        --root-output vmlinux
        --output sbom.spdx.json
