# SPDX-FileCopyrightText: 2025 TNG Technology Consulting GmbH
#
# SPDX-License-Identifier: GPL-2.0-only

services:
  sbom:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace/LinuxKernelSbomGenerator
    working_dir: /workspace/LinuxKernelSbomGenerator
    command: >
      python3 src/sbom.py
        --src-tree ../linux
        --output-tree ../linux/kernel_build
        --root-output-in-tree vmlinux
        --output sbom.spdx.json
