# SPDX-FileCopyrightText: 2025 TNG Technology Consulting GmbH
#
# SPDX-License-Identifier: GPL-2.0-only

name: Build and Publish Devcontainer Image

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/Dockerfile'
  workflow_dispatch:
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/tng/kernel-sbom
          push: always
