# SPDX-FileCopyrightText: 2025 TNG Technology Consulting GmbH
#
# SPDX-License-Identifier: GPL-2.0-only

name: CMD Graph Based Kernel Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tng/kernel-sbom
      options: --user 0

    steps:
      - uses: actions/checkout@v4

      - name: Post Create Setup
        run: |
          ln -s /workspace/linux linux
     
      - name: Build Non-Default Kernel
        run: |
            cd linux
            rm -rf kernel-build
            mkdir kernel-build
            cp /boot/config-$(uname -r) kernel-build/.config
            make olddefconfig O=kernel-build
            make -j$(nproc) O=kernel-build

      - name: Cmd Graph Based Kernel Build
        run: |
          # Generate linux-cmd directory and validate that the kernel can be compiled using only source files referenced in the cmd graph.
          python3 sbom_analysis/cmd_graph_based_kernel_build/cmd_graph_based_kernel_build.py
          cd linux-cmd
          make defconfig O=kernel-build
          make -j$(nproc) O=kernel-build
