# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: 2025 TNG Technology Consulting GmbH

name: CMD Graph Based Kernel Builds

on:
  workflow_dispatch:
    inputs:
      test_archive:
        description: Name of the test archive to download from https://fileshare.tngtech.com/d/e69946da808b41f88047/
        required: false
        default: linux.v6.17.tinyconfig.tar.gz
      use_missing_sources_directory:
        description: whether to use the pre-existing missing_sources_in_cmd_graph.<config>.json files from version control or to regenerate the missing source files from scratch during analysis.
        type: boolean
        default: true
      freeDiskSpace:
        description: whether to free disk space before building the kernel
        type: boolean
        default: false

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        if: ${{ inputs.freeDiskSpace }}

      - uses: actions/checkout@v4

      - name: Install Dependencies and Linux Kernel
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential linux-image-generic linux-headers-generic bc \
              flex bison python3 python3-pip python3-venv git libelf-dev libssl-dev

      - name: Download Linux Kernel Test Data
        run: |
          test_archive="${{ inputs.test_archive }}"
          echo "Downloading $test_archive"
          curl -L -o "$test_archive" "https://fileshare.tngtech.com/d/e69946da808b41f88047/files/?p=%2F$test_archive&dl=1"
          tar -xzf "$test_archive"

      - name: Load missing sources
        if: ${{ inputs.use_missing_sources_directory }}
        run: |
          cd sbom_analysis/cmd_graph_based_kernel_build
          test_archive="${{ inputs.test_archive }}"
          cp "missing_sources/missing_sources_in_cmd_graph.${test_archive%.tar.gz}.json" missing_sources_in_cmd_graph.json

      # Build kernel with the original .config using only source files referenced in the cmd graph
      - name: Create linux_cmd
        run: python3 sbom_analysis/cmd_graph_based_kernel_build/main.py
